apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: env-app
  template:
    metadata:
      labels:
        app: env-app
    spec:
      containers:
        - name: envvars-html
          image: "anilho/envvars:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: user
              value: {{ .Values.env.user | quote }}


